version: "3.9"

services:
  streamlit_app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      # Mount the current folder inside the container
      # so you can quickly update code without rebuilding (optional)
      - .:/app
    # If you want the SQLite DB to persist on the host system, you could do:
    # - ./reservations.db:/app/reservations.db
    environment:
      # If you need environment variables
      # - Example: "production", "dev", etc.
      # - STREAMLIT_ENV=production
      - PYTHONUNBUFFERED=1
